### ISSUE TITLE
Heroku needs location where we can upload advertisements and randomize their appearance on the app.

### ISSUE THREAD

**Issue by LydiaMontagnese** [Givdo/givdo_api_server#28]
When we have new advertisers, we need to be able to upload their advertisements and tell the backend how many times the advertisement should be shown on games before it stops being shown. For example:

Advertiser: [Company Name] <-- text input
Image: [upload button] <-- upload
number of games displayed: [200] <-- number input

**Comment by LydiaMontagnese** [comment]
1) Table that is the ads (column: # of impressions [every time the ad displays it increments the counter], # of clicks)

2) Table that is the users.

3) Joined table of ads and users.

Pick random ad for end of game (as long as user hasn't seen the ad 3 times already).

Option: Mix Panel --> custom events on ads. 

-Table
-Model
-Controller
-API Controller
-ActiveAdmin Page

Additional table for impressions and clicks per user.

**Comment by marz0** [comment]
Will Heroku actually be storing these advertisement images or just storing the links to these images? I assume it's the latter?

**Comment by diegotoral** [comment]
Yeah, those images should be uploaded to a external service like Amazon S3 (which I recommend). I personally recommend [Refile](https://github.com/refile/refile) gem.

**Comment by marz0** [comment]
When is the ad supposed to be displayed to the user? After answering the last question?

**Comment by LydiaMontagnese** [comment]
Yep! Right after every game. There should be an ad screen mockup already in there under templates/quiz/sponsor.html
