### ISSUE TITLE
Error running db:migrate

### ISSUE THREAD

**Issue by balajisubr** [Givdo/givdo_api_server#30]
Greetings everybody,

I am a new volunteer planning to work on this project shortly. I am trying to setup this app locally on my computer and I get an error while running the rake db:migrate command as follows:
:~/givdo_api_server$ rake db:migrate
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'activeadmin'.
Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
Backtrace for gem load error is:
/home/.gem/ruby/2.3.1/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect'
/home/.gem/ruby/2.3.1/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
/home/.gem/ruby/2.3.1/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
Any inputs on getting this resolved would be appreciated.

**Comment by marz0** [comment]
Hi Balaji,

Do you have node installed?

**Comment by balajisubr** [comment]
@marz0 Thanks for pointing out. I have installed Node and it now works. But when I run the following command, it errors out
rake givdo:admin:create
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Email can't be blank, Password can't be blank

**Comment by diegotoral** [comment]
You missed the email and password. Try something like `rake givdo:admin:create["email@example.com","password123"]`
